#!/usr/bin/env bash

set -e

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOTDIR="$(git -C "$SCRIPTDIR" rev-parse --show-toplevel)"

set -x

# see also "https://github.com/moby/moby/blob/master/.mailmap" for how email
# addresses and names are deduplicated

cat > "${ROOTDIR}/AUTHORS" <<- EOF
	# File auto-generated by running generate-authors.sh. DO NOT EDIT.
	# This file lists all contributors to the repository.
	# See generate-authors.sh to make modifications.

	$(git -C "$ROOTDIR" log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf)
EOF
